import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import { useAppData } from '../components/AppShell'
import { SkeletonRows } from '../components/ui/Skeleton'
import { Banner } from '../components/ui/Banner'
import { Icon } from '../components/ui/Icon'
import { timeAgo } from '../timeAgo'
import { useTypeAnywhere } from '../useTypeAnywhere'
import { kelaboKindIcon } from '../kelaboKind'

const WEEK_MS = 7 * 24 * 3600 * 1000
const SEARCH_DEBOUNCE_MS = 250

function durationMin(start, end) {
  if (!start || !end) return null
  return Math.max(1, Math.round((end - start) / 60000))
}

function RecordRow({ r, delay, onRemove }) {
  const mins = durationMin(r.startedAt, r.endedAt)
  const hasMinutes = !!(r.minutes || r.hasMinutes)
  const people = (r.participants || []).length || r.participantCount || 0
  return (
    <Link
      className={'row row-removable anim-in' + (delay ? ` anim-in-d${Math.min(delay, 4)}` : '')}
      to={`/kelabos/${r.archiveId || r.kelaboId}`}
    >
      <Icon name={kelaboKindIcon(r)} size={15} className="kind-icon" />
      <div className="row-main">
        <div className="row-title">
          {r.title}
          {r.titleGenerated && (
            <span className="chip" title="Title generated by the assistant">
              <Icon name="sparkles" size={12} />AI title
            </span>
          )}
          {hasMinutes && (
            <span className="chip" title="Minutes available">
              <Icon name="file-text" size={12} />minutes
            </span>
          )}
        </div>
        <div className="row-sub">
          {people} people{mins ? ` · ${mins} min` : ''} · {r.boardCount ?? 0} board · host: {r.host || 'you'}
        </div>
      </div>
      <span className="row-meta">{timeAgo(r.endedAt || r.startedAt)}</span>
      <button
        className="remove-btn"
        // The row is a <Link>; without this the click navigates to the record
        // we are about to ask permission to delete.
        onClick={e => { e.preventDefault(); e.stopPropagation(); onRemove(r, { skipConfirm: e.shiftKey }) }}
        title={`Remove ${r.title} — hold Shift to skip the confirmation`}
        aria-label={`Remove ${r.title}`}
      >
        <Icon name="x" size={15} />
      </button>
      <span className="row-chevron"><Icon name="chevron-right" /></span>
    </Link>
  )
}

/** A search hit. The server's brief row plus, for a minutes match, the passage
 *  that matched where the detail line would otherwise be. */
function HitRow({ r, delay }) {
  return (
    <Link
      className={'row anim-in' + (delay ? ` anim-in-d${Math.min(delay, 4)}` : '')}
      to={`/kelabos/${r.archiveId}`}
    >
      <Icon name={kelaboKindIcon(r)} size={15} className="kind-icon" />
      <div className="row-main">
        <div className="row-title">
          {r.title}
          {r.matched === 'minutes' && (
            <span className="chip" title="Matched inside the minutes">
              <Icon name="file-text" size={12} />minutes
            </span>
          )}
        </div>
        {r.snippet && <div className="row-sub">{r.snippet}</div>}
      </div>
      <span className="row-meta">{r.endedAt ? timeAgo(r.endedAt) : ''}</span>
      <span className="row-chevron"><Icon name="chevron-right" /></span>
    </Link>
  )
}

export default function Records() {
  // Shared with the rail, so removing a record in either place updates both.
  // Auth is already enforced by the shell route, hence no guard here.
  const { records, recordsError: error, removeRecord } = useAppData()

  // The same search the global dialog runs — titles from the list, full text
  // of the minutes from the archives — mounted on the page that owns records.
  const [q, setQ] = useState('')
  const [hits, setHits] = useState(null) // null = not searching
  const [minutesCapped, setMinutesCapped] = useState(false)
  const [searching, setSearching] = useState(false)
  const searchRef = useRef(null)
  useTypeAnywhere(searchRef)

  useEffect(() => {
    const text = q.trim()
    if (text.length < 2) { setHits(null); setMinutesCapped(false); setSearching(false); return undefined }
    setSearching(true)
    const t = setTimeout(() => {
      api.searchRecords(text)
        .then(r => { setHits(r?.results || []); setMinutesCapped(!!r?.minutesCapped) })
        .catch(() => { setHits([]); setMinutesCapped(false) })
        .finally(() => setSearching(false))
    }, SEARCH_DEBOUNCE_MS)
    return () => clearTimeout(t)
  }, [q])

  const now = Date.now()
  const thisWeek = (records || []).filter(r => now - (r.endedAt || r.startedAt || 0) < WEEK_MS)
  const earlier = (records || []).filter(r => now - (r.endedAt || r.startedAt || 0) >= WEEK_MS)
  const searchingMode = q.trim().length >= 2

  return (
    <main className="page">
      <h1 className="page-title">Kelabos</h1>
      <p className="page-sub">Kelabos you hosted or joined, with their transcript, board and minutes.</p>

      <div className="field">
        <span className="label">Search your kelabos</span>
        <div className="search-box">
          <Icon name="search" size={16} />
          <input
            className="input"
            ref={searchRef}
            placeholder="Title, or anything from the minutes"
            value={q}
            onChange={e => setQ(e.target.value)}
            autoComplete="off"
          />
        </div>
      </div>

      {searchingMode ? (
        <>
          <div className="section-title">Search results</div>
          {searching && hits === null && <SkeletonRows n={2} />}
          {hits !== null && hits.length === 0 && !searching && (
            <div className="empty">Nothing in your titles or minutes matches “{q.trim()}”.</div>
          )}
          {(hits || []).map((r, i) => <HitRow key={r.archiveId} r={r} delay={i} />)}
          {minutesCapped && (
            <p className="text-meta">Minutes of older kelabos were not searched — titles still were.</p>
          )}
        </>
      ) : (
        <>
          {records === null && !error && <SkeletonRows n={4} />}
          {error && <Banner kind="warn">Couldn't load your kelabos — check your connection and reload.</Banner>}
          {records !== null && records.length === 0 && (
            <div className="empty empty-hero">
              <span className="empty-mark" aria-hidden="true"></span>
              Nothing here yet — kelabos appear once they have ended, with their transcript, board and minutes.
            </div>
          )}

          {thisWeek.length > 0 && (
            <>
              <div className="section-title">This week</div>
              {thisWeek.map((r, i) => <RecordRow key={r.archiveId || r.kelaboId} r={r} delay={i} onRemove={removeRecord} />)}
            </>
          )}
          {earlier.length > 0 && (
            <>
              <div className="section-title">Earlier</div>
              {earlier.map((r, i) => <RecordRow key={r.archiveId || r.kelaboId} r={r} delay={i + thisWeek.length} onRemove={removeRecord} />)}
            </>
          )}
        </>
      )}
    </main>
  )
}
